FROM rust:bookworm AS builder
WORKDIR /build
COPY . .
RUN cargo build --release --bin hbbs --bin hbbr

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /build/target/release/hbbs /usr/bin/hbbs
COPY --from=builder /build/target/release/hbbr /usr/bin/hbbr
WORKDIR /root
ENV HOME=/root
EXPOSE 21115 21116 21116/udp 21117 21118 21119
